//
//  ViewController.swift
//  War Card Game
//
//  Created by Karina Macancela on 5/4/19.
//  Copyright © 2019 Karina. All rights reserved.
//

import UIKit

class ViewController: UIViewController {

    // connected the two image view objects from the storyboard as IBOutlet properties
    
    @IBOutlet weak var leftImageView: UIImageView!
    @IBOutlet weak var rightImageView: UIImageView!
    
    // connected the two  label object from the storyboard as IBOutlet properties
    
    @IBOutlet weak var leftScoreLabel: UILabel!
    @IBOutlet weak var rightScoreLabel: UILabel!
    
    // variables to keep score
    
    var leftScore = 0
    var rightScore = 0
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view.
    }
    
    // added an IBAction function which performs at action whenever the deal button object is clicked by user
    
    @IBAction func dealTapped(_ sender: Any) {
        
        // randomizing integers between 2 to 14 (inclusive)
        
        let leftNumber = Int.random(in: 2...14)
        let rightNumber = Int.random(in: 2...14)
        
        // creating a new UI Image object and assigning it to the image property of the leftImageView object when deal button object is clicked by user
        
        // new card image is being randomized based off the random number generated by the constants leftNumber and rightNumber
        
        leftImageView.image = UIImage(named: "card\(leftNumber)")
        
        // doing the same for the image property of the rightImageView object
        
        rightImageView.image = UIImage(named: "card\(rightNumber)")
        
        if leftNumber > rightNumber {
            // left side wins
            
            // increase left side score by 1 and update the text property of the leftScoreLabel object
            
            leftScore += 1
            leftScoreLabel.text = String(leftScore)
        }
        else if leftNumber < rightNumber {
            // right side wins
            
            // increase right side score by 1 and update the text property of the rightScoreLabel object
            
            rightScore += 1
            rightScoreLabel.text = String(rightScore)
        }
        else {
            // tie -- nothing will occur
        }
        
    }
    

}

